language: python
python: "2.7"
services:
  - redis-server
env:
  - REDISCLOUD_URL=redis://localhost:6379
install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
script: py.test
